### PR TITLE
fix: add left padding to TabsManager widget

### LINKED ISSUE #3316: [Bug] Tabs overlap with macOS window controls
### Bug Description

Tabs overlap with macOS window controls when the sidebar is closed.

### How to Reproduce

- Open multiple windows
- Close sidebar

### Expected Behavior

The tabs and window controls don't overlap.

### Operating System

macOS Ventura 13.2.1

### AppFlowy Version(s)

Version 0.3.0 (0.3.0)

### Screenshots

Screenshot 2023-09-01 at 14 35 24

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vincendep**
Fix macOS window controls overlapping with tabbar when side menu is closed.

image

Closes #3316 

---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart [hunk 1]
```diff
@@ -44,7 +44,10 @@ class HomeStack extends StatelessWidget {
           return Column(
             mainAxisAlignment: MainAxisAlignment.start,
             children: [
-              TabsManager(pageController: pageController),
+              Padding(
+                padding: EdgeInsets.only(left: layout.menuSpacing),
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart:48]: The padding is only relevant when the platform is MacOS
