### PR TITLE
fix: the share markdown feature doesn't work in 0.2.0

### LINKED ISSUE #2755: [Bug] the share markdown feature doesn't work in 0.2.0
### Bug Description

the share markdown doesn't work in 0.2.0

### How to Reproduce

1. click the share button

### Expected Behavior

it works fine.

### Operating System

all platforms.

### AppFlowy Version(s)

0.2.0

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by LucasXu0**
### Feature Preview

closes #2755

---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart [hunk 1]
```diff
@@ -1,65 +1,46 @@
...
-          emit(const DocShareState.loading());
-        },
-        shareLink: (ShareLink value) {},
-        shareText: (ShareText value) {},
-      );
-    });
+  DocShareBloc({
+    required this.view,
+  }) : super(const DocShareState.initial()) {
+    on<ShareMarkdown>(_onShareMarkdown);
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart:15]: Is there really a reason to not just put the one line of code here 😂 Instead of creating a private method.

File: frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart [hunk 2]
```diff
@@ -1,39 +1,36 @@
...
       child: BlocListener<DocShareBloc, DocShareState>(
         listener: (context, state) {
-          state.map(
-            initial: (_) {},
-            loading: (_) {},
+          state.mapOrNull(
             finish: (state) {
               state.successOrFail.fold(
-                _handleExportData,
+                (data) => _handleExportData(context, data),
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart:33]:
```suggestion
                (data) {
                  if (data.exportType == ExportType.Markdown) {
                    showSnackBarMessage(
                      context,
                      LocaleKeys.settings_files_exportFileSuccess.tr(),
                    );
                  }
                },
```
Then you can remove `_handleExportData`. If we don't intend to use it at some point at least.

Another option would be to add a snackbar for the two other cases as well. (See below)

File: frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart [hunk 3]
```diff
@@ -52,27 +49,30 @@ class DocumentShareButton extends StatelessWidget {
     );
   }
 
-  void _handleExportData(ExportDataPB exportData) {
+  void _handleExportData(BuildContext context, ExportDataPB exportData) {
     switch (exportData.exportType) {
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart:53]:
```suggestion
  void _handleExportData(BuildContext context, ExportDataPB exportData) {
    String message = switch (exportData.exportType) {
        ExportType.Markdown => LocaleKeys.settings_files_exportFileSuccess.tr(),
        ExportType.Link => LocaleKeys.settings_link_copiedToClipboardSuccess.tr(),
        ExportType.text => LocaleKeys.settings_text_copiedToClipboardSuccess.tr(),
      };
      
      showSnakBarMessage(context, message);
```

File: frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+              const DividerNodeParser(),
+              const MathEquationNodeParser(),
+              const CodeBlockNodeParser(),
+            ],
+          );
+          return right(markdown);
+        case DocumentExportType.text:
+          throw UnimplementedError();
+      }
+    });
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart:56]: Comma for formatting

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart [hunk 5]
```diff
@@ -248,18 +246,17 @@ class _AppFlowyFileExporter {
...
-            if (json != null) {
-              content = jsonEncode(json);
-            }
+          final documentExporter = DocumentExporter(view);
+          final result = await documentExporter.export(
+            DocumentExportType.json,
+          );
+          result.fold((l) => Log.error(l), (json) {
+            content = json;
           });
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart:260]: Comma for formatting

File: frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart [hunk 6]
```diff
@@ -94,20 +94,14 @@ class ShareActionList extends StatelessWidget {
...
             if (exportPath != null) {
               docShareBloc.add(DocShareEvent.shareMarkdown(exportPath));
-              showMessageToast('Exported to: $exportPath');
             }
             break;
-          // case ShareAction.copyLink:
-          //   NavigatorAlertDialog(
-          //     title: LocaleKeys.shareAction_workInProgress.tr(),
-          //   ).show(context);
-          //   break;
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart:110]: We don't really need these comments related to copyLink right?

File: frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart (hunk 1 above)
Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart:15]: the other ones are unused now. It will look more clear to just put one event handler here.

Actually, I want to refactor all the event handlers into this pattern.

The other events are currently unused. IMO, it would be clearer to put the logic inside the single event handler. In fact, I intend to refactor all the event handlers into this pattern.

For example, 

Before
```dart
on<Event>(( ... {
  event.map(....) 
}))
```

After
```dart
on<EventA>(_onEventA);
on<EventB>(_onEventB);
```

File: frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart (hunk 2 above)
Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart:33]: I believe it is better to keep the `_handleExportData` function. The other export logic will be implemented in the future. I don't want the `build` function to become too long.

File: frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart (hunk 3 above)
Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart:53]: The other cases have not been implemented yet, so there is no need to handle them at the moment.

File: frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart (hunk 6 above)
Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart:110]: Yes, there are no current plans for it.

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart (hunk 5 above)
Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_exporter_widget.dart:260]: It is acceptable as long as the CI doesn't raise any issues.

File: frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart (hunk 1 above)
Comment (Xazin) [reply frontend/appflowy_flutter/lib/plugins/document/application/share_bloc.dart:15]: I agree with using the Events without freezed union, but whether the event handler is inside the `on<EventA>` or not doesn't make much sense, there's no reason to declare a private method, it's readable as is.
