### PR TITLE
fix: date field created when reference a calendar

### LINKED ISSUE #2891: [Bug] inline calendar date duplication
### Bug Description

issue 1 : so everytime a "new calender" or a "referenced calender" is created, it adds a new "date" property

### How to Reproduce

Create a calendar and add a few events
Reference it in a document
There is a duplicated Date field created, which is not intended

### Expected Behavior

Don't create extra Date properties 

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.3

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
fixes #2891 

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/rust-lib/flowy-database2/src/manager.rs [hunk 1]
```diff
@@ -194,12 +194,18 @@ impl DatabaseManager2 {
...
-              .with_layout_setting(layout_setting);
+            Some((Some(field), layout_setting)) => {
+              params = params
+                .with_deps_fields(vec![field])
+                .with_layout_setting(layout_setting);
+            },
+            Some((None, layout_setting)) => {
+              params = params.with_layout_setting(layout_setting);
+            },
+            _ => {},
```
Comment (LucasXu0) [inline frontend/rust-lib/flowy-database2/src/manager.rs:208]: Suggestion:

```rs
if let Some(field) = field {
  params = params.with_deps_fields(vec![field]);
}
params = params.with_layout_setting(layout_setting);
```

No need to match again.

Comment (richardshiue) [reply frontend/rust-lib/flowy-database2/src/manager.rs]: Got it, thanks!
