### PR TITLE
fix: arrow keys on field name text field

### LINKED ISSUE #3158: [Bug] -> doesn't work when editing a property name
### Bug Description

image

### How to Reproduce

Click on a property name
Try to use -> to move the cursor from the very beginning

### Expected Behavior

I can use -> to move the cursor

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.8

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
resolves #3158

Also makes the cursor begin at the end of the text in a FlowyTextField if an initial value is provided.

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart [hunk 1]
```diff
@@ -174,39 +175,28 @@ class _FieldNameTextFieldState extends State<FieldNameTextField> {
         focusNode.unfocus();
       }
     });
-
-    super.initState();
   }
 
   @override
   Widget build(BuildContext context) {
-    return BlocListener<FieldEditorBloc, FieldEditorState>(
```
Comment (appflowy) [inline frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/header/field_editor.dart:183]: The name might be changed by other devices. So it needs to set the name if it's modified
