### PR TITLE
fix: default text direction not synced

### LINKED ISSUE #5402: [Bug] Text direction settings not working
### Bug Description

`defaultTextDirection` is not getting updated.

### How to Reproduce

Open settings go to the workspace section and change the text direction to RTL you should see all the text in the document to get RTL but it doesn't happen anything.

### Expected Behavior

all the text in the document should start from right to left.

### Operating System

Linux

### AppFlowy Version(s)

v0.5.8

### Screenshots

_No response_

### Additional Context

I think this bug came after the settings have changed, I'm not sure. Please assign it to me. I want to add some tests to maybe prevent this from happening again.

### PR DESCRIPTION
**Pull request by zoli**
resolves #5402

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart [hunk 1]
```diff
@@ -387,19 +387,24 @@ class _WorkspaceIconSetting extends StatelessWidget {
   }
 }
 
-class _TextDirectionSelect extends StatelessWidget {
-  const _TextDirectionSelect();
+class TextDirectionSelect extends StatelessWidget {
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart:390]: Let's add the `@visibleForTesting` on this class.

File: frontend/appflowy_flutter/test/widget_test/direction_setting_test.dart [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+    implements AppearanceSettingsCubit {}
+
+class MockDocumentAppearanceCubit extends Mock
+    implements DocumentAppearanceCubit {}
+
+class MockDocumentAppearance extends Mock implements DocumentAppearance {}
+
+void main() {
+  // ignore: unused_local_variable
+  late AppFlowyUnitTest context;
```
Comment (Xazin) [inline frontend/appflowy_flutter/test/widget_test/direction_setting_test.dart:29]: Unused?

**Review by Xazin — APPROVED** [review]

**Review by Xazin — APPROVED** [review]
