### PR TITLE
fix: slash menu responds to multiple key events

### LINKED ISSUE #2030: [Bug] Slash menu responds to multiple key commands.
### Bug Description

https://user-images.githubusercontent.com/44445638/226263547-1511b257-2836-41a6-bdbb-77a140fa0d01.mp4

The video shows that the slash menu responds to the tab and arrow keys. The user should be able to control the slash menu simultaneously with the tab and arrow keys.   

### How to Reproduce

Type `/` in a document. Move the selection using the arrow keys, then press tab.

### Expected Behavior

The tab key should move the currently highlighted selection to the right by one. You can move to the first element in the next row if the selection is at the button furthest to the right. Using the arrow keys, the selection should move in the direction specified by the arrow key.

### Operating System

Windows 10

### AppFlowy Version(s)

main

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by squidrye**
The slash menu responded to the tab and arrow keys however the user should be able to control the slash menu simultaneously with the tab and arrow keys. This PR fixes the issue.

Tab key now moves the currently highlighted selection to the right by one. User can move to the first element in the next row if the selection is at the button furthest to the right. Using the arrow keys, the selection moves in the direction specified by the arrow key.

https://user-images.githubusercontent.com/84044317/226590005-b5e1aae8-cc6d-4e63-85ec-80bb401e46c4.mp4

fixes #2030

### CODE REVIEW

File: frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/selection_menu/selection_menu_widget.dart [hunk 1]
```diff
@@ -339,7 +339,18 @@ class _SelectionMenuWidgetState extends State<SelectionMenuWidget> {
...
       newSelectedIndex += 1;
+    }else if (event.logicalKey == LogicalKeyboardKey.tab) {
+      newSelectedIndex += widget.maxItemInRow;
+      var currRow = (newSelectedIndex) % widget.maxItemInRow;
+      if (newSelectedIndex >= _showingItems.length) {
+        if (currRow + 1 >= widget.maxItemInRow) {
+          newSelectedIndex = 0;
+        } else {
+          newSelectedIndex = (currRow + 1);
+        }
```
Comment (a-wallen) [inline frontend/appflowy_flutter/packages/appflowy_editor/lib/src/render/selection_menu/selection_menu_widget.dart:350]:
```suggestion
newSelectedIndex = (curRow + 1) % widget.maxItemInRow;
```

**Comment by LucasXu0** [comment]
Hey, @squidrye. Please add the tests code both.

**Comment by squidrye** [comment]
Will do @LucasXu0

**Review by a-wallen — APPROVED** [review]
[Nice.](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)
