### PR TITLE
chore: fix the select option mouse event conflict

### LINKED ISSUE #4002: [Bug] Select option button has mouse event conflicts
### Bug Description

Clicking on the extra button sometimes opens the menu, other times select the option, sometimes both, sometimes nothing. The behavior is especially bad on the row detail page.

https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/5d905167-c152-4bf9-9bd4-52263d9eaedd

### How to Reproduce

Follow the video above

### Expected Behavior

It shouldn't be like this

### Operating System

macOS

### AppFlowy Version(s)

0.3.8

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
fixes #4002 

also includes some code cleanup

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_editor.dart [hunk 1]
```diff
@@ -260,9 +260,9 @@ class _CreateOptionCell extends StatelessWidget {
                 child: SelectOptionTag(
                   name: name,
                   color: AFThemeExtension.of(context).greyHover,
-                  onSelected: () => context
-                      .read<SelectOptionCellEditorBloc>()
-                      .add(SelectOptionEditorEvent.newOption(name)),
+                  // onSelected: () => context
+                  //     .read<SelectOptionCellEditorBloc>()
+                  //     .add(SelectOptionEditorEvent.newOption(name)),
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/cells/select_option_cell/select_option_editor.dart:265]: Why commented out?

**Review by Xazin — APPROVED** [review]
Love the commit message
