### PR TITLE
Fix launch review issues

### LINKED ISSUE #3412: [Bug] text alignment-related issues
### Bug Description

- [x] unable to trigger the text-align item when selecting text.
- [x] the active mode of the outline block in the dark mode doesn’t have a good contrast
- [x] text change for 'show rename dialog when creating a new file'
- [x] switch looks ugly

### How to Reproduce

run the code in the latest main branch

### Operating System

All Platform

### AppFlowy Version(s)

0.3.2

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by LucasXu0**
### Feature Preview

closes #3412

Screenshot 2023-09-15 at 16 02 24
Screenshot 2023-09-15 at 15 56 25

Screenshot 2023-09-15 at 16 02 20
Screenshot 2023-09-15 at 15 41 00

Screenshot 2023-09-13 at 17 09 21

---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart [hunk 1]
```diff
@@ -167,16 +167,21 @@ class OutlineItemWidget extends StatelessWidget {
...
-        onTap: () => scrollToBlock(context),
-        child: Container(
-          padding: EdgeInsets.only(left: node.leftIndent),
-          child: Text(
-            node.outlineItemText,
-            style: style,
+      builder: (context, onHover) {
+        return GestureDetector(
+          onTap: () => scrollToBlock(context),
+          child: Container(
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart:173]:
```suggestion
          child: Padding(
```

**Review by Xazin — APPROVED** [review]
