### PR TITLE
fix: mobile row detail title not being updated

### LINKED ISSUE #4504: [Bug] Mobile Editing Database Cards do not save
### Bug Description

When editing a database entry in eg. a Grid, where it's possible to navigate between items in a carousel like manner, when changing the Title of the item, it doesn't get saved. It only saves on the item you quit on.

### How to Reproduce

1. Open AppFlowy
2. Create or Open a Grid
3. Click on the primary cell of any row to open the Dialog
4. Change the title of one item
5. Move to next item
6. Change the title of that item
7. Press the `x` to close dialog
8. Only the last item you changed title of, has saved the change

### Expected Behavior

1. Open AppFlowy
2. Create or Open a Grid
3. Click on the primary cell of any row to open the Dialog
4. Change the title of one item
5. Move to next item
6. Change the title of that item
7. Press the `x` to close dialog
8. Any item you changed the title of should have been saved

### Operating System

MacOS

### AppFlowy Version(s)

0.4.4

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/04b7c798-8eb0-4d57-bc9e-7621f5d48db4

### Additional Context

Debounce for auto save

### PR DESCRIPTION
**Pull request by richardshiue**
resolves #4504

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart [hunk 1]
```diff
@@ -420,6 +420,7 @@ class _TitleSkin extends IEditableTextCellSkin {
             fontSize: 23,
             fontWeight: FontWeight.w500,
           ),
+      onChanged: (text) => bloc.add(TextCellEvent.updateText(text)),
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart:423]: What do you think about using a debounce?

Comment (richardshiue) [reply frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart:423]: Yes I agree. I put it it in the text cell bloc here

image

Comment (Xazin) [reply frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart:423]: Amazing

**Review by Xazin — APPROVED** [review]
