### PR TITLE
fix: apply formatting to pasted text only when the block is a paragraph

### LINKED ISSUE #4905: [FR] When pasting text into an empty blcok with formatting, is it possible to not replace the block style?
### Description

When pasting text into an empty blcok with formatting, is it possible to not replace the block style?

For example, in an empty H1, pasting text will be replaced with text style. I want it to maintain the style of H1. The same is true for other formats, which is more in line with most people's operating habits.

### Impact

The empty block style will not change into the format I don’t want.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by q200892907**
### Feature Preview

fix #4905 

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/editor_state_paste_node_extension.dart [hunk 1]
```diff
@@ -14,7 +14,7 @@ extension PasteNodes on EditorState {
     final transaction = this.transaction;
     final insertedDelta = insertedNode.delta;
     // if the node is empty, replace it with the inserted node.
```
Comment (LucasXu0) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/editor_state_paste_node_extension.dart:16]: Please update the comment too.
