### PR TITLE
fix: chaning field type #5360

### LINKED ISSUE #5360: [Bug] changing field type from text to checkbox causes exception
### Bug Description

In board view changing field type from text to checkbox throws an exception when you hover the cursor on the card.
`'CellController<CheckboxCellDataPB, String>' is not a subtype of type 'CellController<String, String>' in type`

### How to Reproduce

Open a card and create new field which its type is text by default. Change the field type to checkbox and close the card. Hover on any card and you get exception.
converting any field from `CellController<String, String>` to a `CellController<SomeCellDataPB, String>` causes exception.

### Expected Behavior

Not throwing any exception.

### Operating System

Linux

### AppFlowy Version(s)

v0.5.7

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zoli**
Before this changing any field from CellController<String, String> to a CellController<SomeCellDataPB, String> caused an exception. The root of the problem was that _CardContent wasn't getting rebuilt when field type got changed. In CardState it was storing a list of CellContext which contains only field id and row id so on changing field type the state wasn't changing.
I made a new type CellMeta which stores field type alongside row id and field id and now CardState stores list of CellMeta.

Fixes #5360

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Review by Xazin — APPROVED** [review]

File: frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart [hunk 1]
```diff
@@ -116,33 +117,54 @@ List<CellContext> _makeCells(
         !(fieldInfo.visibility?.isVisibleState() ?? false) ||
         (groupFieldId != null && cellContext.fieldId == groupFieldId);
   });
-  return cellContexts.toList();
+  return cellContexts
+      .map(
+        (cellCtx) => CellMeta(
+          fieldId: cellCtx.fieldId,
+          rowId: cellCtx.rowId,
+          fieldType: fieldController.getField(cellCtx.fieldId)!.fieldType,
```
Comment (LucasXu0) [inline frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart:125]: A future improvement: We are force unwrapping the value from `getField` everywhere. This doesn't make sense. If we are sure the value must not be null, we should change the return type of the `getField` function.
