### PR TITLE
fix: open-ai replace does not work in certain use-cases

### LINKED ISSUE #2092: [Bug] OpenAi replace does not work in certain use-cases
### Bug Description

As the title suggests, replace option when using OpenAi to generate a summary or fix-spelling does not work as expected in few use-cases, if response generated is multiline, last line overwrites the previous lines. This can cause much problem and confusion if user is working on large selections of text for correction or summary generation.

### How to Reproduce

1. Select some text on editor (likely a query to generate multiple lines from open ai)
2. select summarize and then replace the selected text.

### Expected Behavior

Selected text should be correctly replaced by the response generated by open-ai.

### Operating System

Linux

### AppFlowy Version(s)

Version 0.1.1 (1)

### Screenshots

https://user-images.githubusercontent.com/84044317/227204772-9077f453-4994-41da-9618-5ae431cac55e.mp4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by squidrye**
Replacing lesser number of available multi-line text nodes with higher number of incoming multi-line nodes lead to inconsistencies such as overwriting and unexpected line skips, this PR fixes the issue.

fixes #2092

### CODE REVIEW

File: frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart [hunk 1]
```diff
@@ -396,15 +404,23 @@ extension TextTransaction on Transaction {
...
+                ),
+              ]);
+            } else {
+              document.insert(path, [
+                TextNode(
+                  delta: Delta()..insert(text),
+                ),
+              ]);
             }
-            insertNode(path, TextNode(delta: Delta()..insert(text)));
```
Comment (squidrye) [inline frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart:405]: This was more complicated than I thought, existing insertNode function transformed paths, which in case of raise issue caused unexpected line skips and loss of data after selection in the same path (line), so I ended up using document.insert() which seemed to work fine.

Comment (LucasXu0) [reply frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart:405]: Actually, you should not use `document.insert` to update the document content. The only way to update it is through operations, like insertNode, deleteNode, and so on.

Comment (squidrye) [reply frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart:405]: Alright, I'll try to work it out.

Comment (squidrye) [reply frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/transform/transaction.dart:405]: I got it to work thanks for review @LucasXu0

**Comment by LucasXu0** [comment]
Hey, @squidrye. I reimplement some parts of your code and formatted the code. Please take a look. https://github.com/AppFlowy-IO/AppFlowy/pull/2100/commits/6b13358cfc9d741ebdac9f71c965b138d2fe900f
