### PR TITLE
fix: added missing hover tooltip to toolbar item

### LINKED ISSUE #3690: [Bug] Missing the hover tooltip in the RTL mode
### Bug Description

image

### How to Reproduce

Text layout : RTL
Select text to trigger the format menu
Hover on the last icon "T"
No tooltip hint

### Expected Behavior

Has hint like other options

### Operating System

macOS

### AppFlowy Version(s)

v0.3.5

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Kritarthsharma**
### Fixes #3690 

Added missing hint for the remaining options.

https://github.com/AppFlowy-IO/AppFlowy/assets/42487588/0a11df44-f95d-4a5c-b979-90a4ee551934

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart [hunk 1]
```diff
@@ -34,12 +36,18 @@ final customizeFontToolbarItem = ToolbarItem(
...
+          child: SVGIconItemWidget(
+            size: const Size.square(18),
+            tooltip: LocaleKeys.document_plugins_fonts.tr(),
+            isHighlight: false,
+            highlightColor: highlightColor,
+            iconBuilder: (_) => const FlowySvg(
+              FlowySvgs.font_family_s,
+              size: Size.square(16.0),
+              color: Colors.white,
+            ),
```
Comment (LucasXu0) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart:50]:
```suggestion
          child: FlowyTooltip(
            message: LocaleKeys.document_plugins_fonts.tr(),
            child: const FlowySvg(
              FlowySvgs.font_family_s,
              size: Size.square(16.0),
              color: Colors.white,
            ),
          ),
```

**Review by LucasXu0 — APPROVED** [review]
