### PR TITLE
fix(flutter): implement mention date transaction handler

### LINKED ISSUE #6913: [Bug] Reminder can't be deleted
### Bug Description

If you created reminder you can't delete it

### How to Reproduce

1. Create reminder
2. Delete reminder
3. It will be always in info panel and no option to delete it. There are a lot of notification this the same title  
they always shown as active

### Expected Behavior

1. Create reminder
2. Delete reminder
3. It will not appear in notification panel

### Operating System

macOs

### AppFlowy Version(s)

0.7.5

### Screenshots

https://github.com/user-attachments/assets/34ecab13-a117-4cda-827c-8d00e2e35573

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
resolve #6913

~~TODO: fix, test~~ (done)

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Review by Xazin — APPROVED** [review]

File: frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart [hunk 1]
```diff
@@ -0,0 +1,259 @@
...
+        MentionBlockKeys.reminderId: reminderId,
+        MentionBlockKeys.includeTime: data.includeTime,
+        MentionBlockKeys.reminderOption: data.reminderOption.name,
+      },
+    };
+
+    // The index is the index of the delta, to get the index of the mention character
+    // in all the text, we need to calculate it based on the deltas before the current delta.
+    int mentionIndex = 0;
+    for (final (i, delta) in node.delta!.indexed) {
```
Comment (LucasXu0) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart:204]: Don't force unwrap the delta here.

Comment (richardshiue) [reply frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart:204]: Can I early return if it's null? I thought the mention would live inside a delta

Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart:204]: Yeah. If the delta is null, ignore this transaction. In the common case, the mention must be in the delta. To avoid using force unwrap is to prevent crash or assertion.

Comment (richardshiue) [reply frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart:208]: Got it, I've made the corresponding change. Thanks!
