### PR TITLE
fix: add shortcut to create Inline Math Equation

### LINKED ISSUE #7331: [FR] Inline math equation keyboard shortcut
### Description

A keyboard shortcut for the inline math equation (e.g. like Notion Ctrl + Shift + E by default)

### Impact

For people that use a lot of inline math equations (e.g. students in maths or computer science taking lecture notes) formatting would be a lot faster :)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by asjqkkkk**
To fix #7331 

- Insert inline math eqaution : ctrl + shift + e
- Align text center: ctrl + shift + e -> ctrl + shift + c

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by LucasXu0** [comment]
> A keyboard shortcut for the inline math equation (e.g. like Notion Ctrl + Shift + E by default)

The keyboard shortcut should be for the inline math equation, not the math equation block.

macOS: cmd+shift+e
Linux/Windows: ctrl+shift+e

Screenshot 2025-02-21 at 14 32 57

**Comment by asjqkkkk** [comment]
Oh I see, I'll update this PR

> cmd

Oh I see, I'll update the code

File: frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_shortcut.dart [hunk 1]
```diff
@@ -0,0 +1,74 @@
+import 'package:appflowy/generated/locale_keys.g.dart';
+import 'package:appflowy/plugins/document/presentation/editor_plugins/plugins.dart';
+import 'package:appflowy_editor/appflowy_editor.dart';
+import 'package:easy_localization/easy_localization.dart';
+import 'package:flutter/material.dart';
+
+/// Windows / Linux : ctrl + shift + e
+/// macOS           : ctrl + shift + e
```
Comment (LucasXu0) [inline frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_shortcut.dart:8]:
```suggestion
/// macOS           : cmd + shift + e
```
