### PR TITLE
fix:  favorite selection and context menu doesn't work

### LINKED ISSUE #3113: [Bug] Favorites context menu doesn't work
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/38805008-3651-4108-a489-2eece63e7012

### How to Reproduce

Try to unpin a favorited page

### Expected Behavior

I'm able to remove a page from Favorites

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.8

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by squidrye**
### Feature Preview

https://github.com/AppFlowy-IO/AppFlowy/assets/84044317/872e1cd4-9562-43e7-8fab-f898a4b3d774

fixes #3113 
---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart [hunk 1]
```diff
@@ -215,8 +218,11 @@ class _SingleInnerViewItemState extends State<SingleInnerViewItem> {
       ),
       buildWhenOnHover: () => !widget.showActions,
       builder: (_, onHover) => _buildViewItem(onHover),
-      isSelected: () => (widget.showActions ||
-          getIt<MenuSharedState>().latestOpenView?.id == widget.view.id),
+      isSelected: () =>
+          (widget.isDraggable ||
+              widget.categoryType == FolderCategoryType.favorite) &&
+          (widget.showActions ||
+              getIt<MenuSharedState>().latestOpenView?.id == widget.view.id),
```
Comment (squidrye) [inline frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart]: @LucasXu0, this logic change in last commit didn't incorporate favorites, since draggable is not yet available for favorites it would always be false thus breaking selection and menu, I have added the condition

**Comment by LucasXu0** [comment]
@squidrye I have updated the code and added a new parameter named `isFeedback` to distinguish the `isSelected` status. 

Please include the corresponding test for this case.
