### PR TITLE
Fix: Null check error in FlowyHoverContainer

### LINKED ISSUE #2147: [Bug] Null check error in FlowyHoverContainer
### Bug Description

Null check error in FlowyHoverContainer

https://user-images.githubusercontent.com/14248245/228915676-d2d95626-096b-44b5-b94e-da43a873706e.mov

### How to Reproduce

1. Create a grid page
2. Open any row as a page
3. Hover on the page

### Expected Behavior

No error occur

### Operating System

macOS

### AppFlowy Version(s)

0.1.1

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hyj1204**
I added a `SizedBox.shrink()` when there is no child in the `FlowyHoverContainer` in order to prevent the null check error happen again. Meanwhile, I delete the `_background` widget since it doesn't show any UI effect anyway. 

Fixes #2147 

https://user-images.githubusercontent.com/14248245/228919011-4dea812b-4356-4d75-b573-cb9ca5d04d12.mov

### CODE REVIEW

File: frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart [hunk 1]
```diff
@@ -151,7 +151,7 @@ class FlowyHoverContainer extends StatelessWidget {
               .iconTheme
               .copyWith(color: Theme.of(context).colorScheme.onSurface),
         ),
-        child: child!,
+        child: child ?? const SizedBox.shrink(),
```
Comment (Xazin) [inline frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart:154]: Why even render the `Theme` with a SizedBox.shrink() if it has no use?

```
    if (child == null) {
      return const SizedBox.shrink();
    }

    final hoverBorder = Border.all(
      color: style.borderColor,
      width: style.borderWidth,
    );

    return Container(
      margin: style.contentMargin,
      decoration: BoxDecoration(
        border: hoverBorder,
        color: style.hoverColor ?? Theme.of(context).colorScheme.secondary,
        borderRadius: style.borderRadius,
      ),
      child:
          //override text's theme with new color when it is hovered
          Theme(
        data: Theme.of(context).copyWith(
          textTheme: Theme.of(context).textTheme.copyWith(
                bodyMedium: Theme.of(context)
                    .textTheme
                    .bodyMedium
                    ?.copyWith(color: Theme.of(context).colorScheme.onSurface),
              ),
          iconTheme: Theme.of(context)
              .iconTheme
              .copyWith(color: Theme.of(context).colorScheme.onSurface),
        ),
        child: child!,
```
I would do this instead, and if you still want the Container to be displayed, then I'd do this:
```
    final hoverBorder = Border.all(
      color: style.borderColor,
      width: style.borderWidth,
    );

    return Container(
      margin: style.contentMargin,
      decoration: BoxDecoration(
        border: hoverBorder,
        color: style.hoverColor ?? Theme.of(context).colorScheme.secondary,
        borderRadius: style.borderRadius,
      ),
      child: child == null ? const SizedBox.shrink() :
          Theme(
        data: Theme.of(context).copyWith(
          textTheme: Theme.of(context).textTheme.copyWith(
                bodyMedium: Theme.of(context)
                    .textTheme
                    .bodyMedium
                    ?.copyWith(color: Theme.of(context).colorScheme.onSurface),
              ),
          iconTheme: Theme.of(context)
              .iconTheme
              .copyWith(color: Theme.of(context).colorScheme.onSurface),
        ),
        child: child!,
```

**Review by a-wallen — APPROVED** [review]
LGTM. PR only contains API changes and code removal, not sure if it warrants having a test since we're only making the child parameter required.

**Comment by LucasXu0** [comment]
> LGTM. PR only contains API changes and code removal, not sure if it warrants having a test since we're only making the child parameter required.

LGTM. I think the test is not required here.
