### PR TITLE
fix: height for calendar view in document

### LINKED ISSUE #2806: [Bug] inline cal area too small
### Bug Description

image

### How to Reproduce

Create a calendar inside a document

### Expected Behavior

enough space for viewing a month of events

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.1

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
title says all, resolves #2806 

image

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by Xazin** [comment]
How does the calendar reference and calendar size the height of each cell when there's multiple events?

I'm curious to know if the whole row resizes to fit width, or if we could make it so? _(Within some boundaries so that it's not infinite)._

**Comment by richardshiue** [comment]
Hi @Xazin, the calendar component we're using stretches out horizontally and then based on the aspect ratio provided (0.6 in this case), calculate the height of each cell. If `useAvailableSpace` is specified, the cell aspect ratio is calculated using the constraint's maxHeight. Individual cells cannot dynamically change its height based on its contents, only by resizing the overall calendar component. Therefore, when there are multiple events in a cell, I'm forced to make them live in a listview and let them scroll.

> I'm curious to know if the whole row resizes to fit width

I'm not sure if I got your question. As I understand it, the calendar already fits the width and the cells are distributed along that x axis

**Comment by Xazin** [comment]
> Hi @Xazin, the calendar component we're using stretches out horizontally and then based on the aspect ratio provided (0.6 in this case), calculate the height of each cell. If `useAvailableSpace` is specified, the cell aspect ratio is calculated using the constraint's maxHeight. Individual cells cannot dynamically change its height based on its contents, only by resizing the overall calendar component. Therefore, when there are multiple events in a cell, I'm forced to make them live in a listview and let them scroll.
> 
> 
> 
> > I'm curious to know if the whole row resizes to fit width
> 
> 
> 
> I'm not sure if I got your question. As I understand it, the calendar already fits the width and the cells are distributed along that x axis
> 
> 
> 
> 

Ah yes, meant height there.

File: frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart [hunk 1]
```diff
@@ -175,19 +168,27 @@ class _CalendarPageState extends State<CalendarPage> {
...
-    return Expanded(
-      child: Padding(
-        padding: GridSize.contentInsets,
-        child: MonthView(
+  Widget _buildCalendar(
+    BuildContext context,
+    EventController eventController,
+    int firstDayOfWeek,
+  ) {
+    final isInDocument = context.read<DocumentBloc?>() != null;
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: I'm not sure if I like this. I think I'd prefer a field in the `CalendarPage` eg. `bool shrinkWrap` or `bool fixedHeight`.

Comment (richardshiue) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: Good idea, how would you do this? I still need the build context so it has to be in the build method. Or do you mean passing in the bool in the constructor? I don't think that's a bad idea since other database views could also benefit from this, but I don't want to make the code for DatabaseViewWidget complicated just for the calendar.

Comment (Xazin) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: I see what you mean. Let me check what other options we have.

Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: @Xazin @richardshiue Any updates? If not, I would prefer a solution that involves adding a parameter called 'shrinkWrap'.

Comment (Xazin) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: I think it's fine to default `shrinkWrap` to false, and then in the relevant database block builder simply set it to true.

Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: Sounds good to me. @richardshiue What do you think of this solution?

Comment (richardshiue) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: I'm a bit confused. Do you mean we pass shrinkwrap through constructors from database_view_block_component down to calendar_page? I wanna make sure before I commit

Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart:176]: Yes. Use shrinkWrap instead of the isInDocumrnt to identify whether the database view needs more space or not.

**Review by Xazin — APPROVED** [review]
