### PR TITLE
test: fix calendar integration test #2919

### LINKED ISSUE #2919: [Bug] calendar integration tests are failing
### Bug Description

Title says all

### How to Reproduce

Run the calendar integration tests

### Expected Behavior

All tests passing

### Operating System

Fedora Linux 38

### AppFlowy Version(s)

latest main

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
The integration test in Github Actions have only passed from time to time, and has recently completely given up running on my local machine. This PR aims to fix that.

resolves #2919

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/integration_test/database_calendar_test.dart [hunk 1]
```diff
@@ -220,17 +221,22 @@ void main() {
...
-      // Edit the event's date
-      final tomorrow = DateTime.now().add(const Duration(days: 1));
-      await tester.selectDay(content: tomorrow.day);
+      // Edit the event's date. To avoid selecting a day outside of the current month, the new date will be one day closer to the middle of the month.
+      DateTime newDate;
+      if (today.day < 15) {
+        newDate = today.add(const Duration(days: 1));
+      } else {
+        newDate = today.subtract(const Duration(days: 1));
+      }
```
Comment (LucasXu0) [inline frontend/appflowy_flutter/integration_test/database_calendar_test.dart:230]:
```suggestion
      final newDate = today.day < 15
          ? today.add(const Duration(days: 1))
          : today.subtract(const Duration(days: 1));
```
