### PR TITLE
fix: some database bugs

### LINKED ISSUE #5209: [Bug]  [create at] cells no more auto setting date in 0.5.5
### Bug Description

in new version 0.5.5 in database [create at] cells not auto setting date for creating new rows?

### How to Reproduce

by creating a new database using [create at] type cell

### Expected Behavior

find out the problem and fix it

### Operating System

windows10 professional

### AppFlowy Version(s)

0.5.5

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
support

image

resolves #5209

also fix another bug where all the toasts in the app aren't working.

### Feature Preview

---

#### PR Checklist

- [ ] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

File: frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart [hunk 1]
```diff
@@ -214,29 +214,19 @@ class MobileURLEditor extends StatelessWidget {
...
+      await InternetAddress.lookup(uri.host);
+    }
   } catch (_) {
-    url = "https://www.google.com/search?q=${Uri.encodeComponent(content)}";
+    uri = Uri.parse(
+      "https://www.google.com/search?q=${Uri.encodeComponent(content)}",
+    );
   } finally {
-    await afLaunchUrlString(url);
+    await launchUrl(uri);
```
Comment (Xazin) [inline frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart:230]:
```suggestion
    await afLaunchUrl(uri);
```

**Review by Xazin — APPROVED** [review]

File: frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart (hunk 1 above)
Comment (richardshiue) [reply frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart:230]: @Xazin @LucasXu0 While I was implementing this logic, I didn't like the behavior with `afLaunchUrl`'s `addingHttpSchemeWhenFailed` in certain cases. If I don't provide a scheme and I call it after parsing it, like below

```
final uri = Uri.parse('instagram.com');
await afLaunchUrl(uri, addingHttpSchemeWhenFailed: true);
```

`afLaunchUrl` tries to immediately launch it. When that fails or returns false, it then adds the http scheme and retry, resulting in this even though on the second try the link launches successfully.

image

So here in this function, I did the handling myself and removed the need for `afLaunchUrl`. I also needed to support searching with google if the link cannot open.

How should I proceed? Should I make any changes to `afLaunchUrl?

Comment (LucasXu0) [reply frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart:230]: > I also needed to support searching with google if the link cannot open.

This logic should not be included in `afLaunchUrl` function. I have reviewed your changes. It's ok to keep your logic.

> afLaunchUrl tries to immediately launch it. When that fails or returns false, it then adds the http scheme and retry, resulting in this even though on the second try the link launches successfully.

I suggest skipping the first return if addingHttpSchemeWhenFailed is set to true.
