### PR TITLE
fix: close popover after item selection in settings view

### LINKED ISSUE #3318: [FR] Close context menus when an item is selected in settings
### Description

Context menus usually close when an item is selected.

In AppFlowy settings they tend to not do that, which is inconsistent with the conventions on most platforms.

https://github.com/AppFlowy-IO/AppFlowy/assets/86030/1815301b-b1c9-4768-8537-4a1cf38dd718

### Impact

- Better meets user expectations
- Improves consistency with platform conventions

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vincendep**
### Feature Preview

closes #3318 
---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by richardshiue** [comment]
Hi @vincendep, thanks for contributing. Instead of passing the `PopoverController` everywhere, you can simply call `PopoverContainer.of(context).close()`. It will make the code more lean

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart [hunk 1]
```diff
@@ -127,7 +133,7 @@ class _ThemeFontFamilySettingState extends State<ThemeFontFamilySetting> {
                     FlowySvgs.check_s,
                   )
                 : null,
-        onTap: () {
+        onTap: () async {
```
Comment (MayurSMahajan) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart:136]: why mark this async?
controller.close() does not return Future

**Review by MayurSMahajan — CHANGES_REQUESTED** [review]

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart (hunk 1 above)
Comment (vincendep) [reply frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart:136]: Hi...but DocumentAppearanceCubit::syncFontFamily does. I've missed the await on that line (I suggest to add the unawaited_futures lint rule).

Comment (MayurSMahajan) [reply frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart:136]: Thanks for clarifying.

**Comment by vincendep** [comment]
> Hi @vincendep, thanks for contributing. Instead of passing the `PopoverController` everywhere, you can simply call `PopoverContainer.of(context).close()`. It will make the code more lean

Hi @richardshiue. Changes done.

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart (hunk 1 above)
Comment (richardshiue) [reply frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart:134]: I don't think it quite makes sense to use async/await in an onTap handler.

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart [hunk 2]
```diff
@@ -127,16 +131,18 @@ class _ThemeFontFamilySettingState extends State<ThemeFontFamilySetting> {
...
               buttonFontFamily) {
             context
                 .read<AppearanceSettingsCubit>()
                 .setFontFamily(parseFontFamilyName(style.fontFamily!));
-            context
+            await context
                 .read<DocumentAppearanceCubit>()
                 .syncFontFamily(parseFontFamilyName(style.fontFamily!));
           }
+          popover.close();
```
Comment (richardshiue) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart:145]: This can be a single line. `PopoverContainer.of(context).close()`

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme_setting.dart [hunk 3]
```diff
@@ -147,15 +162,16 @@ class ColorSchemeUploadPopover extends StatelessWidget {
...
                   ? const FlowySvg(
                       FlowySvgs.check_s,
                     )
                   : null,
-              onTap: () {
-                if (currentTheme != theme) {
-                  context.read<AppearanceSettingsCubit>().setTheme(theme);
+              onTap: () async {
+                if (widget.currentTheme != theme) {
+                  await context.read<AppearanceSettingsCubit>().setTheme(theme);
```
Comment (richardshiue) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme_setting.dart:172]: Same. No need to use async/await

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme_setting.dart [hunk 4]
```diff
@@ -107,7 +116,11 @@ class ColorSchemeUploadPopover extends StatelessWidget {
                   children: [
                     ...AppTheme.builtins
                         .map(
-                          (theme) => _themeItemButton(context, theme.themeName),
+                          (theme) => _themeItemButton(
+                            context,
+                            controller,
```
Comment (richardshiue) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/color_scheme_setting.dart:121]: It probably isn't necessary to pass the controller here since you're in the same scope

**Review by richardshiue — CHANGES_REQUESTED** [review]

**Comment by richardshiue** [comment]
Hi @vincendep! There are some merge conflicts here, could you have a look at them?

File: frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart [hunk 5]
```diff
@@ -30,28 +30,34 @@ class SettingsLanguageView extends StatelessWidget {
   }
 }
 
-class LanguageSelector extends StatelessWidget {
+class LanguageSelector extends StatefulWidget {
```
Comment (richardshiue) [inline frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart:33]: Why you want to switch to stateful widget? Is something broken?

Comment (vincendep) [reply frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_language_view.dart]: Nope, that is a refuse from the initial implementation using PopoverControllers. Restored to StatelessWidget.

**Comment by richardshiue** [comment]
Got it. If that's the case, could you do the same for the ThemeValueDropdown?

**Review by richardshiue — APPROVED** [review]
LGTM
