### PR TITLE
fix: newly-created rows aren't being automatically sorted

### LINKED ISSUE #4600: [Bug] Newly inserted rows aren't being sorted
### Bug Description

Title says all

### How to Reproduce

1. Go to a grid
2. Add a sort
3. Create a new row from
4. See that the row isn't immediately sorted

### Expected Behavior

It should be

### Operating System

macOS

### AppFlowy Version(s)

0.4.6

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
resolves #4600

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Review by Xazin — APPROVED** [review]
Let's add a test for this specific case so we don't end up breaking it again :eyes: :pray: What do you think @richardshiue ?

**Comment by richardshiue** [comment]
> Let's add a test for this specific case so we don't end up breaking it again 👀 🙏 What do you think @richardshiue ?

I'm not against writing tests, but this is way too specific. I think it's better to refactor this code so that the field controller's `FieldInfo`s get updated whenever something related happens.

**Review by Xazin — APPROVED** [review]

**Review by LucasXu0 — APPROVED** [review]

File: frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs [hunk 1]
```diff
@@ -195,6 +218,7 @@ async fn assert_sort_changed(
           old_row_orders.insert(changed.new_index, old);
           assert_eq!(old_row_orders, new_row_orders);
         },
+        DatabaseViewChanged::InsertSortedRowNotification(_changed) => {},
```
Comment (Xazin) [inline frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs:221]: Redundant

**Review by Xazin — APPROVED** [review]
